services:
  
  integration-db:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "9999:5432"
    command: -p 5432
    volumes:
      - /tablespaces/tables
      - /tablespaces/indexes

networks:
  default: